<?php if( !defined( '_VALID_MOS' ) && !defined( '_JEXEC' ) ) die( 'Direct Access to '.basename(__FILE__).' is not allowed.' );
/*
*
* @copyright Copyright (C) 2007 - 2010 RuposTel - All rights reserved.
* @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php
* One Page checkout is free software released under GNU/GPL and uses code from VirtueMart
* VirtueMart is free software. This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
* 
*/

mm_showMyFileName(__FILE__); 
global $VM_LANG;

$VM_LANG->load('admin');
$VM_LANG->load('order');
$VM_LANG->load('common');
$VM_LANG->load('shop');

global $jmshortcode;
if (!empty($jmshortcode) && (is_object($jmshortcode)))
$lang = $jmshortcode->shortcode;


$iter = 0;


/*
 Anything before and after this template is generated by a template file /pages/shop.cart.tpl.php of your VM template
 There you can change page title from Cart to Checkout and erase any text and button that are genereated under the checkout page 
*/
echo $op_basket; // will show either basket/basket_b2c.html.php or basket/basket_b2b.html 
echo $op_coupon; // will show coupon if enabled from common/couponField.tpl.php with corrected width to size
//echo $html_in_between; // from configuration file.. if you don't want it, just comment it or put any html here to explain how should a customer use your cart, update quantity and so on


?>


<?php if (!empty($google_checkout_button)) { ?>
<div id="op_google_checkout" style="float: right; clear: both; width: 100%; padding-top: 10px;">
 <?php echo $google_checkout_button;  // will load google checkout button if you have powersellersunite.com/googlecheckout installed
 ?>
</div>
<?php } ?>

<br style="clear: both;" />
<!-- start main onepage div, if javascript fails it will remain hidden -->
<div class="dob0log">





<!-- start of checkout form -->
<form action="<?php $action_url; ?>" method="post" name="adminForm">
    <div class="dob1">
        <!-- user info details -->
        <h4><?php 
		$iter++;
		echo $iter.'. '.JText::_('COM_VIRTUEMART_USER_FORM_BILLTO_LBL'); ?> </h4>
        <?php echo $op_userfields; ?>
        
        <!-- end of user info details -->
        <!-- ship to address details -->
        <?php if (NO_SHIPTO != '1') { ?>
        
        <?php 
		
		$iter++;
		echo '<h4>'.$iter.'. Ship to information </h4>';
		echo $op_shipto; // user data and his shipping addresse, they are fetched from checkout/get_shipping_address.tpl.php ?>
        
        
        <?php } ?>
        <!-- end ship to address details -->
        
        
    </div>
    
    <div class="dob2">
	<!-- shipping methodd -->
	<h4><?php $iter++; echo $iter.'. '; echo $VM_LANG->_('PHPSHOP_ORDER_PRINT_SHIPPING_LBL'); ?></h4>
        <div id="ajaxshipping">
        <?php echo $shipping_method_html; // this prints all your shipping methods from checkout/list_shipping_methods.tpl.php ?>
        </div>
        <!-- end shipping methodd -->
        <?php if (!empty($op_payment))
            {
            ?>

            <h4><?php $iter++; echo $iter.'. '; echo "Select Payment" ?> </h4>



            <?php echo $op_payment; ?>
            
            
            
            <?php 
            } 
            ?>
        
    </div>
    
    <div class="dob3">
<h4><?php $iter++; echo $iter.'. '; echo $VM_LANG->_('PHPSHOP_ORDER_CONFIRM_MNU') ?></h4>
<div id="onepage_total_inc_sh">
<div id="totalam">
<div id="tt_order_subtotal_div"><span id="tt_order_subtotal_txt" class="bottom_totals_txt"></span><span id="tt_order_subtotal" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_order_payment_discount_before_div"><span id="tt_order_payment_discount_before_txt" class="bottom_totals_txt"></span><span class="bottom_totals" id="tt_order_payment_discount_before"></span><br class="op_clear"/></div>
<div id="tt_order_discount_before_div"><span id="tt_order_discount_before_txt" class="bottom_totals_txt"></span><span id="tt_order_discount_before" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_shipping_rate_div"><span id="tt_shipping_rate_txt" class="bottom_totals_txt"></span><span id="tt_shipping_rate" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_shipping_tax_div"><span id="tt_shipping_tax_txt" class="bottom_totals_txt"></span><span id="tt_shipping_tax" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_tax_total_0_div"><span id="tt_tax_total_0_txt" class="bottom_totals_txt"></span><span id="tt_tax_total_0" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_tax_total_1_div"><span id="tt_tax_total_1_txt" class="bottom_totals_txt"></span><span id="tt_tax_total_1" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_tax_total_2_div"><span id="tt_tax_total_2_txt" class="bottom_totals_txt"></span><span id="tt_tax_total_2" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_tax_total_3_div"><span id="tt_tax_total_3_txt" class="bottom_totals_txt"></span><span id="tt_tax_total_3" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_tax_total_4_div"><span id="tt_tax_total_4_txt" class="bottom_totals_txt"></span><span id="tt_tax_total_4" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_order_payment_discount_after_div"><span id="tt_order_payment_discount_after_txt" class="bottom_totals_txt"></span><span id="tt_order_payment_discount_after" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_order_discount_after_div"><span id="tt_order_discount_after_txt" class="bottom_totals_txt"></span><span id="tt_order_discount_after" class="bottom_totals"></span><br class="op_clear"/></div>
<div id="tt_total_div"><span id="tt_total_txt" class="bottom_totals_txt"></span><span id="tt_total" class="bottom_totals"></span><br class="op_clear"/></div>
</div>
<div class="op_hr" >&nbsp;</div>
</div>

                           
	   
                            <h4><?php $iter++; echo $iter.'. '; echo JText::_('COM_VIRTUEMART_ORDER_REGISTER_GUEST_CHECKOUT');  ?></h4>
        
        <!-- customer note box -->
         <div style="width: 100%; float: left;">
							 <span id="customer_note_input" class="">
								<label for="customer_note_field"><?php echo JText::_('COM_VIRTUEMART_COMMENT'); ?>:</label>
							   <textarea rows="3" cols="30" name="customer_note" id="customer_note_field" ></textarea>
							
							 </span>
							 <br style="clear: both;" />
							 
          </div>
        <!-- end of customer note -->
        <!-- some little tricks for virtuemart classes -->
        <input type="hidden" name="checkout_last_step" value="1" /><input type="hidden" name="page" value="checkout.onepage" /><input type="hidden" name="onepage" value="1" /><input type="hidden" name="checkout_this_step[]" value="CHECK_OUT_GET_SHIPPING_METHOD" /><input type="hidden" name="checkout_this_step[]" value="CHECK_OUT_GET_PAYMENT_METHOD" /><input type="hidden" name="checkout_this_step[]" value="CHECK_OUT_GET_FINAL_CONFIRMATION" />
        <!-- end of tricks -->
        <!-- show TOS and checkbox before button -->
     
                                     	 <div id="rbsubmit" style="width: 100%; float: right;">
                        	   <!-- show total amount at the bottom of checkout and payment information, don't change ids as javascript will not find them and OPC will not function -->
<div id="onepage_info_above_button">

<?php
/*
 content of next divs will be changed by javascript, please don't change it's id, you may freely format it and if you add any content of txt fields it will not be overwritten by javascript 
*/
?>
<?php 
/*
* END of order total at the bottom
*/
?>


<!-- content of next div will be changed by javascript, please don't change it's id -->
 
<!-- end of total amount and payment info -->
<!-- submit button -->
 <br />
 
 <!-- show TOS and checkbox before button -->
<?php
	
if ($tos_required)
{
if ($show_full_tos) { ?>
<!-- show full TOS -->
	<textarea id="onepage_tos" readonly="readonly" cols="40" rows="10">
<?php echo $tos_con; ?></textarea>
<!-- end of full tos -->
<?php } 


{

?>
	<div id="agreed_div" class="formLabel " style="text-align: left;">
	<input value="1" type="checkbox" id="agreed_field" name="tosAccepted" <?php if (!empty($agree_checked)) echo ' checked="checked" '; ?> class="terms-of-service" <?php if (VmConfig::get('agree_to_tos_onorder', 1)) echo ' required="required" '; ?> autocomplete="off" />

					<label for="agreed_field"><?php echo JText::_('COM_VIRTUEMART_I_AGREE_TO_TOS'); 
					if (!empty($tos_link))
					{
					?><a target="_blank" href="<?php echo $tos_link; ?>" onclick="javascript: return op_openlink(this); " ><br />(<?php echo JText::_('COM_VIRTUEMART_CART_TOS'); ?>)</a><?php } ?></label>
				
		<strong>* </strong> 
	</div>
	<div class="formField" id="agreed_input">
</div>


<?php
}

}
?>

<!-- end show TOS and checkbox before button -->

 <div>
 <div id="payment_info"></div>
	<button id="confirmbtn_button" type="submit" <?php echo $op_onclick; ?> ><h4 id="confirmbtn"><?php echo $VM_LANG->_('PHPSHOP_ORDER_CONFIRM_MNU') ?></h4></button>
 </div>
<br style="clear: both;"/>
</div>
<!-- end of submit button -->




                        	 </div>   

      
            </div>

<!-- end of submit button -->





        
</form>


<!-- end of checkout form -->
<!-- end of main onepage div, if javascript fails it will remain hidden -->

    </div>
<div id="tracking_div"></div>

